project:
  type: website

execute:
  freeze: auto

website:
  sidebar: 
    style: "docked"
    contents:
      - index.qmd
      - src/Lecture_01.qmd
      #- src/Lecture_02.qmd
      #- src/Lecture_03.qmd
      #- src/Lecture_04.qmd
      #- src/Lecture_05.qmd
      #- src/Lecture_06.qmd
      #- src/Lecture_07.qmd
      #- src/Lecture_08.qmd
      #- src/Lecture_09.qmd
      #- src/Lecture_10.qmd
      #- src/Lecture_11.qmd
      #- src/Lecture_12.qmd
      #- src/Lecture_13.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true