project:
  type: website

website:
  sidebar: 
    style: "docked"
    contents:
      - index.qmd
      - src/Chapter_03.qmd
      - src/Chapter_04.qmd
      - src/Chapter_05.qmd
      - src/Chapter_06.qmd
      - src/Chapter_06_1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true