---
title: "1. Numerical Integration"
format: html
editor: visual
execute:
  echo: false
  warning: false
  error: false
---

```{r}
library(devtools)
```


```{r}
#| echo: true
#| message: false

install_github("j-buss/RSSim")
library(RSSim)
```


# Numerical Integration

# Chapter 3 - Random Numbers

## 3.1 Pseudorandom number generation

### Multiplicative Congruential Method

Also known as a [Lehmer random number generator](https://en.wikipedia.org/wiki/Lehmer_random_number_generator).

$$
x_n = a x_{n-1} \,\text{mod}\, m
$$

The limits on the parameters are: $0 < x_0 <m$

If we use the values

-   $a = 2$
-   $m = 7$
-   $x_0 = 6$

We have:

|                $X$                 |
|:----------------------------------:|
|              $x_0=6$               |
| $x_1=5=2 \cdot 6 \;\text{mod}\; 7$ |
| $x_2=3=2 \cdot 5 \;\text{mod}\; 7$ |
| $x_3=6=2 \cdot 3 \;\text{mod}\; 7$ |


```{r}
lehmer.seq
```

```{r}
lehmer.seq(x0=6, a=2, m=7, iterations = 10)
```

```{r}
lehmer.rng
```

```{r}
lehmer.rng(x0=10, a=9, m=4, iterations=19)
```


#### Mixed Congruential Method

[Linear congruential generator](https://en.wikipedia.org/wiki/Linear_congruential_generator) (LCG):


```{r}
lcg.seq
```

```{r}
#lcg.seq()
```


```{r}
lcg.rng
```


```{r}
lcg.rng(x0=3, a=5, c=7, m=200)
```

```{r}
#lcg(1)
```

## 3.2 Using Random numbers to Evaluate Integrals
